name: atol_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - matplotlib=3.1.2
  - numpy=1.17.4
  - pandas=0.25.3
  - scikit-learn=0.21.3
  - tqdm=4.40.0
  - GUDHI=3.0.0
  - joblib=0.14.0
  - scipy=1.3.1
  - pip:
      - giotto-learn==0.1.3
      - networkx==2.4
      - pysmiles==1.0.0







